fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=3000"]
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: detect-private-key
      - id: trailing-whitespace
      - id: requirements-txt-fixer

  - repo: https://github.com/ambv/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3.11

  - repo: local
    hooks:
      - id: isort
        name: isort-local
        entry: pipenv run isort
        language: python
        types: [python]
        pass_filenames: true