version: "3.2"

volumes:
  postgres_data: {}
  redis_data: {}

services:
  redis:
    build: ./docker/redis/
    restart: on-failure
    container_name: ${PROJECT_NAME}_redis
    image: ${PROJECT_NAME}_redis
    volumes:
      - redis_data:/data
    networks:
      - default_dom5
    ports:
      - "${DOCKER_REDIS_PORT}:6379"

networks:
  default_dom5:
    ipam:
      driver: default
